# Camel configuration
camel.main.name = camel-apicuro-setup
camel.main.routes-include-pattern = classpath:camel/*.xml

# Kafka configuration
kafka.brokers = localhost:9092

# Apicurio Registry configuration
apicurio.registry.url = http://localhost:8080/apis/registry/v2

# Log level
logging.level.org.apache.camel = INFO
